#!/usr/bin/env bash
#
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Enforces tag names to have the format `[component]/v[version]`.

# Documentation from `pre-push.sample`:
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>

set -Eeufo pipefail

regexp='^[a-z][0-9a-z_-]+\/v[0-9]+\.[0-9]+\.[0-9]+[^ ]*'

while read -r _ local_oid _ _ ; do
  tags="$(git tag --points-at "$local_oid")"
  if [ -z "$tags" ]; then
    # No tags
    exit 0
  fi
  while IFS= read -r tag; do
    if [[ ! $tag =~ $regexp ]]; then
      >&2 echo "Tag name \"$tag\" does not match format \"[component]/v[version]\""
      >&2 echo "Regular expression: ${regexp}"
      exit 1
    fi
  done <<< "$tags"
done
