#!/usr/bin/env bash
#
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Enforces branch names to have the format `[component]/[feature]`,
# unless it is the default `main` branch.

set -Eeufo pipefail

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = 'main' ]; then
  exit 0
fi

regexp='^[a-z][0-9a-z_-]+\/[a-z][0-9a-z_-]+$'

if [[ ! $branch =~ $regexp ]]; then
  >&2 echo "Branch name \"$branch\" does not match format \"[component]/[feature]\""
  >&2 echo "Regular expression: ${regexp}"
  exit 1
fi
