# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v3
kind: Config
metadata:
  name: go
  annotations:
    config.kubernetes.io/local-config: "true"
profiles:
- name: tls-cert-manager
  activation:
  - kubeContext: kind.* # use cert-manager by default for kind Kubernetes clusters
- name: tls-gke-workload-certs
  activation:
  - kubeContext: gke.* # use GKE workload TLS certificates by default for GKE clusters
requires:
- path: control-plane-go
- path: greeter-go
- path: k8s/envoy
---
apiVersion: skaffold/v3
kind: Config
metadata:
  name: java
  annotations:
    config.kubernetes.io/local-config: "true"
profiles:
- name: tls-cert-manager
  activation:
  - kubeContext: kind.* # use cert-manager by default for kind Kubernetes clusters
- name: tls-gke-workload-certs
  activation:
  - kubeContext: gke.* # use GKE workload TLS certificates by default for GKE clusters
requires:
- path: control-plane-java
- path: greeter-java
- path: k8s/envoy
---
apiVersion: skaffold/v3
kind: Config
metadata:
  name: go-td
  annotations:
    config.kubernetes.io/local-config: "true"
profiles:
- name: traffic-director
- name: traffic-director-off-gcp
requires:
- path: greeter-go
---
apiVersion: skaffold/v3
kind: Config
metadata:
  name: java-td
  annotations:
    config.kubernetes.io/local-config: "true"
profiles:
- name: traffic-director
- name: traffic-director-off-gcp
requires:
- path: greeter-java
